# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CPI_Clean.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Interface_Picture_clean(object):
    def setupUi(self, Interface_Picture_clean):
        Interface_Picture_clean.setObjectName("Interface_Picture_clean")
        Interface_Picture_clean.resize(900, 560)
        self.ComboFrameUnit = QtWidgets.QWidget(Interface_Picture_clean)
        self.ComboFrameUnit.setGeometry(QtCore.QRect(0, 0, 901, 141))
        self.ComboFrameUnit.setObjectName("ComboFrameUnit")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ComboFrameUnit)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DuplicatePhotoShow = QtWidgets.QTableView(self.ComboFrameUnit)
        self.DuplicatePhotoShow.setObjectName("DuplicatePhotoShow")
        self.horizontalLayout.addWidget(self.DuplicatePhotoShow)
        self.CheckArea = QtWidgets.QFrame(self.ComboFrameUnit)
        self.CheckArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CheckArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CheckArea.setObjectName("CheckArea")
        self.gridLayout = QtWidgets.QGridLayout(self.CheckArea)
        self.gridLayout.setObjectName("gridLayout")
        self.button_check = QtWidgets.QPushButton(self.CheckArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_check.sizePolicy().hasHeightForWidth())
        self.button_check.setSizePolicy(sizePolicy)
        self.button_check.setMinimumSize(QtCore.QSize(75, 75))
        self.button_check.setObjectName("button_check")
        self.gridLayout.addWidget(self.button_check, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.CheckArea)

        self.retranslateUi(Interface_Picture_clean)
        QtCore.QMetaObject.connectSlotsByName(Interface_Picture_clean)

    def retranslateUi(self, Interface_Picture_clean):
        _translate = QtCore.QCoreApplication.translate
        Interface_Picture_clean.setWindowTitle(_translate("Interface_Picture_clean", "聊天图片-重复图片清理"))
        self.button_check.setText(_translate("Interface_Picture_clean", "勾选"))
