# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CPI_Search.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Interface_Picture_Search(object):
    def setupUi(self, Interface_Picture_Search):
        Interface_Picture_Search.setObjectName("Interface_Picture_Search")
        Interface_Picture_Search.resize(900, 560)
        Interface_Picture_Search.setSizeIncrement(QtCore.QSize(0, 0))
        Interface_Picture_Search.setBaseSize(QtCore.QSize(0, 0))
        self.label = QtWidgets.QLabel(Interface_Picture_Search)
        self.label.setGeometry(QtCore.QRect(230, 50, 421, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Interface_Picture_Search)
        self.label_2.setGeometry(QtCore.QRect(370, 460, 101, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(Interface_Picture_Search)
        self.radioButton.setGeometry(QtCore.QRect(490, 460, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.pushButton_2 = QtWidgets.QPushButton(Interface_Picture_Search)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 490, 901, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget = QtWidgets.QWidget(Interface_Picture_Search)
        self.widget.setGeometry(QtCore.QRect(200, 160, 481, 241))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 200))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)

        self.retranslateUi(Interface_Picture_Search)
        QtCore.QMetaObject.connectSlotsByName(Interface_Picture_Search)

    def retranslateUi(self, Interface_Picture_Search):
        _translate = QtCore.QCoreApplication.translate
        Interface_Picture_Search.setWindowTitle(_translate("Interface_Picture_Search", "聊天图片-人脸搜索"))
        self.label.setText(_translate("Interface_Picture_Search", "在此处传入一张或多张图像"))
        self.label_2.setText(_translate("Interface_Picture_Search", "人脸组合选项"))
        self.pushButton_2.setText(_translate("Interface_Picture_Search", "搜索人脸"))
        self.pushButton.setText(_translate("Interface_Picture_Search", "上传"))
