# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegisterInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Interface_Register(object):
    def setupUi(self, Interface_Register):
        Interface_Register.setObjectName("Interface_Register")
        Interface_Register.resize(300, 400)
        self.NavigationBar = QtWidgets.QWidget(Interface_Register)
        self.NavigationBar.setGeometry(QtCore.QRect(0, 0, 300, 30))
        self.NavigationBar.setObjectName("NavigationBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.NavigationBar)
        self.horizontalLayout_2.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.titleText = QtWidgets.QLabel(self.NavigationBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleText.sizePolicy().hasHeightForWidth())
        self.titleText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.titleText.setFont(font)
        self.titleText.setObjectName("titleText")
        self.horizontalLayout_2.addWidget(self.titleText)
        self.gap = QtWidgets.QFrame(self.NavigationBar)
        self.gap.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gap.setObjectName("gap")
        self.horizontalLayout_2.addWidget(self.gap)
        self.button_close = QtWidgets.QPushButton(self.NavigationBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_close.sizePolicy().hasHeightForWidth())
        self.button_close.setSizePolicy(sizePolicy)
        self.button_close.setMinimumSize(QtCore.QSize(30, 30))
        self.button_close.setText("")
        self.button_close.setObjectName("button_close")
        self.horizontalLayout_2.addWidget(self.button_close)
        self.label = QtWidgets.QLabel(Interface_Register)
        self.label.setGeometry(QtCore.QRect(0, 30, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.QRcodeShow = QtWidgets.QWidget(Interface_Register)
        self.QRcodeShow.setGeometry(QtCore.QRect(60, 120, 191, 191))
        self.QRcodeShow.setObjectName("QRcodeShow")

        self.retranslateUi(Interface_Register)
        QtCore.QMetaObject.connectSlotsByName(Interface_Register)

    def retranslateUi(self, Interface_Register):
        _translate = QtCore.QCoreApplication.translate
        Interface_Register.setWindowTitle(_translate("Interface_Register", "登录"))
        self.titleText.setText(_translate("Interface_Register", "WeChat gadget"))
        self.label.setText(_translate("Interface_Register", "手机微信扫码登录"))
